/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParadeRouteImport } from './routes/parade'
import { Route as MapRouteImport } from './routes/map'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as DayShareRouteImport } from './routes/day-share'
import { Route as IndexRouteImport } from './routes/index'

const ParadeRoute = ParadeRouteImport.update({
  id: '/parade',
  path: '/parade',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const DayShareRoute = DayShareRouteImport.update({
  id: '/day-share',
  path: '/day-share',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-share': typeof DayShareRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/parade': typeof ParadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-share': typeof DayShareRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/parade': typeof ParadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day-share': typeof DayShareRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/parade': typeof ParadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day-share' | '/itinerary' | '/map' | '/parade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day-share' | '/itinerary' | '/map' | '/parade'
  id: '__root__' | '/' | '/day-share' | '/itinerary' | '/map' | '/parade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayShareRoute: typeof DayShareRoute
  ItineraryRoute: typeof ItineraryRoute
  MapRoute: typeof MapRoute
  ParadeRoute: typeof ParadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parade': {
      id: '/parade'
      path: '/parade'
      fullPath: '/parade'
      preLoaderRoute: typeof ParadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-share': {
      id: '/day-share'
      path: '/day-share'
      fullPath: '/day-share'
      preLoaderRoute: typeof DayShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayShareRoute: DayShareRoute,
  ItineraryRoute: ItineraryRoute,
  MapRoute: MapRoute,
  ParadeRoute: ParadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
